#!/usr/bin/env ruby

require 'benchmark/ips'
require 'matrix'
require 'nmatrix'

Benchmark.ips do |x|
  first_rows  = 10
  first_cols  = 20
  second_rows = 20
  second_cols = 40

  first_array  = Array.new(first_rows) { Array.new(first_cols) { rand } }
  second_array = Array.new(second_rows) { Array.new(second_cols) { rand } }
  result_array = Array.new(first_rows) { Array.new(second_cols) }

  x.report "Array iterative" do
    0.upto(first_rows-1) do |row_number|
      0.upto(second_cols-1) do |col_number|
        product = 0.0
        0.upto(first_cols-1) do |ix|
          product += (first_array[row_number][ix]*second_array[ix][col_number])
        end
        result_array[row_number][col_number] = product
      end
    end
    result_array
  end

  first_matrix  = Matrix[*first_array]
  second_matrix = Matrix[*second_array]

  x.report "MRI Matrix#*" do
    first_matrix * second_matrix
  end

  first_nmatrix  = NMatrix[*first_array, dtype: :float64]
  second_nmatrix = NMatrix[*second_array, dtype: :float64]

  x.report "NMatrix#dot(float64)" do
    first_nmatrix.dot(second_nmatrix)
  end

  first_nmatrix_object  = NMatrix[*first_array, dtype: :object]
  second_nmatrix_object = NMatrix[*second_array, dtype: :object]

  x.report "NMatrix#dot(object)" do
    first_nmatrix_object.dot(second_nmatrix_object)
  end
  x.compare!
end
